# For configuration options, see 
#   https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: DS_PROMETHEUS_UID
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
  - name: Loki
    type: loki
    access: proxy 
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
  - name: ExternalAlertmanager
    type: alertmanager
    url: http://alertmanager:9093
    access: proxy
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
    basicAuth: true
    isDefault: false
  - name: Postgres
    type: postgres
    url: postgres:5432
    user: my_data_user
    secureJsonData:
      password: "my_data_pwd"
    jsonData:
      database: my_data_db
      sslmode: 'disable' 
      postgresVersion: 1500
      timescaledb: false