apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: cpu-hog-experiment
  namespace: chaos-apps
spec:
  appinfo:
    appns: chaos-apps
    applabel: "app=nginx"
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
  - name: pod-cpu-hog
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: '60'
        - name: CPU_CORES
          value: '1'
        - name: CHAOS_INTERVAL
          value: '10'
        - name: TARGET_CONTAINER
          value: 'nginx'
