global:
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_password_file: '/etc/alertmanager/smtp_auth_password'
  smtp_from: your_mail@gmail.com
  smtp_auth_username: your_mail@gmail.com
  smtp_auth_identity: your_mail@gmail.com

templates:
- '/etc/alertmanager/templates/*.tmpl'

route:
  receiver: "discord-default"
  group_by: [alertname, service]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m
  routes:
    - match:
        severity: critical
      receiver: "discord-critical"
      group_wait: 5s
      repeat_interval: 2m
    - match:
        severity: warning
      receiver: "discord-warnings"
      group_wait: 10s
      repeat_interval: 3m
    - match:
        service: payment
      receiver: "discord-payment"
      group_wait: 5s
      repeat_interval: 1m
    - match:
        service: system
      receiver: "discord-system"
      group_wait: 10s
      repeat_interval: 3m

receivers:
  - name: "discord-default"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1378468656245117059/y2NYQi4z6clqKxnk4aywPkmYX8Ot_o_7Do4Hcj1Ye0ZWsQJpMB4HBBhAuUSyzxZv7TRA/slack"
        send_resolved: true
        title: '{{ template "discord.title" . }}'
        text: '{{ template "discord.text" . }}'
        
  - name: "discord-critical"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1378468656245117059/y2NYQi4z6clqKxnk4aywPkmYX8Ot_o_7Do4Hcj1Ye0ZWsQJpMB4HBBhAuUSyzxZv7TRA/slack"
        send_resolved: true
        title: '🔥 CRITICAL ALERT'
        text: '{{ template "discord.critical" . }}'
        
  - name: "discord-warnings"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1378468656245117059/y2NYQi4z6clqKxnk4aywPkmYX8Ot_o_7Do4Hcj1Ye0ZWsQJpMB4HBBhAuUSyzxZv7TRA/slack"
        send_resolved: true
        title: '⚠️ WARNING ALERT'
        text: '{{ template "discord.warning" . }}'
        
  - name: "discord-payment"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1378468656245117059/y2NYQi4z6clqKxnk4aywPkmYX8Ot_o_7Do4Hcj1Ye0ZWsQJpMB4HBBhAuUSyzxZv7TRA/slack"
        send_resolved: true
        title: '💳 PAYMENT ALERT'
        text: '{{ template "discord.payment" . }}'
        
  - name: "discord-system"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1378468656245117059/y2NYQi4z6clqKxnk4aywPkmYX8Ot_o_7Do4Hcj1Ye0ZWsQJpMB4HBBhAuUSyzxZv7TRA/slack"
        send_resolved: true
        title: '🖥️ SYSTEM ALERT'
        text: '{{ template "discord.system" . }}'